### ISSUE TITLE
✨ 엑셀에 참여, 신규 인원 필드 추가

### ISSUE THREAD

**Issue by ChooSeoyeon** [FISOLUTION/police-backend#101]
## 📌 Feature Issue
- 엑셀 다운로드하면 신규인원, 참여인원 필드도 볼 수 있다.

## 📝 To-do
- [x] 엑셀 생성 시 필드 추가

**Comment by solitair** [comment]
프론트엔드에서 자체적으로 처리하도록 합니다.
