### ISSUE TITLE
🐛 Cross Domain 간 쿠키 전송 이슈 해결

### ISSUE THREAD

**Issue by ChooSeoyeon** [FISOLUTION/police-backend#89]
## 📌 Feature Issue
- 현재 인증 인가 시스템이 세션 방식으로 구성되어 있다.
- 세션은 서로 같은 도메인 혹은 서브도메인에서 호스팅되어야지만 공유가 가능하다.
- prod 서버는 프론트엔드와 백엔드의 도메인이 서브 도메인 관계라 세션 공유에 문제가 없었다.
- 허나, dev 서버의 경우 백엔드만 사용하고 프론트엔드는 local에서 실행시키고 있어 세션 공유를 하지 못하는 문제가 있었다.
- 이로 인해 백엔드 실행 파일을 프론트엔드에 넘겨주어 프론트 측에서 백엔드를 직접 local에서 함께 실행 시켜 개발을 진행하고 있다는 큰 불편함이 존재했다. 용량이 큰 jar 파일을 매번 직접 넘겨줘야 했기에 병목이 불가피했다.
- 이 고질적인 문제를 해결하기 위해 인증 인가 시스템을 토큰 방식으로 전환할까도 고민했지만
- 일단 더 빠르게 적용할 수 있는 방법을 찾았다. 
- 쿠키 설정을 통해 서로 다른 도메인 간에도 전송 가능하게 해주는 것이다.
- 이 방법이 동작하지 않는다면 프록시 서버를 사용해보려 한다. 
- 이 방법 역시 동작하지 않는다면 jwt 토큰 방식으로의 전환을 속히 진행할 것이다.

## 📝 To-do
- [x] 쿠키에 `SameSite=None;Secure` 설정 추가

**Comment by uwoobeat** [comment]
@ChooSeoyeon  쿠기 -> 쿠키로 수정

**Comment by ChooSeoyeon** [comment]
https://jfbta.tistory.com/96

**Comment by ChooSeoyeon** [comment]
https://stackoverflow.com/questions/7319093/how-do-i-use-sessions-across-subdomains-on-localhost

**Comment by ChooSeoyeon** [comment]
/etc/hosts

**Comment by ChooSeoyeon** [comment]
https://stackoverflow.com/questions/4845050/localhost-cookie

**Comment by ChooSeoyeon** [comment]
https://developers.google.com/search/blog/2020/01/get-ready-for-new-samesitenone-secure?hl=ko
